services:
  auth-service:
    build: ./auth-service
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/authdb
      - JWT_SECRET=supersecret
    depends_on:
      - mongo

  resource-service:
    build: ./resource-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://mongo:27017/roommanager_resources
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - resource-service

volumes:
  mongo-data: